name: proyecto_bt7274
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter_markdown: 0.7.7+1
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_database: ^11.3.10
  firebase_auth: ^5.2.0

  cloud_firestore: ^5.4.0
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  cloud_functions: ^5.6.2
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  encrypt: ^5.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  assets:
    - docs/privacy/AVISO_PRIVACIDAD_v1.0.md
    - docs/privacy/PROTECCION_DATOS_v1.0.md
    - docs/privacy/DOCUMENTO_ARCO_v1.0.md
    - .env

  uses-material-design: true
